@extends(($params->isAjax ? 'layouts.ajax' : 'layouts.master'))

@section('content')

<main>
	<section class="staticWrapper">
		<h1 class="headerStyle">Internet Radio Privacy Policy:</h1>
			<p>Internet Radio ("Internet Radio") operates Internet Radio and may operate other websites. It is Internet Radio Radio policy to respect your privacy regarding any information we may collect while operating our websites.</p>
		<h2>Website Visitors</h2>
			<p>Like most website operators, Internet Radio Radio collects non-personally-identifying information of the sort that web browsers and servers typically make available, such as the browser type, language preference, referring site, and the date and time of each visitor request. Internet Radio Radio purpose in collecting non-personally identifying information is to better understand how Internet Radio Radio visitors use its website. From time to time, Internet Radio Radio may release non-personally-identifying information in the aggregate, e.g., by publishing a report on trends in the usage of its website.
			Internet Radio Radio also collects potentially personally-identifying information like Internet Protocol (IP) addresses for logged in users and for users leaving comments on Internet Radio Radio blogs/sites. Internet Radio Radio only discloses logged in user and commenter IP addresses under the same circumstances that it uses and discloses personally-identifying information as described below, except that commenter IP addresses and email addresses are visible and disclosed to the administrators of the blog/site where the comment was left.</p>
		<h2>Gathering of Personally-Identifying Information</h2>
			<p>Certain visitors to Internet Radio Radio websites choose to interact with Internet Radio Radio in ways that require Internet Radio Radio to gather personally-identifying information. The amount and type of information that Internet Radio Radio gathers depends on the nature of the interaction. For example, we ask visitors who sign up at Internet Radio Radio to provide a username and email address. Those who engage in transactions with Internet Radio Radio are asked to provide additional information, including as necessary the personal and financial information required to process those transactions. In each case, Internet Radio Radio collects such information only insofar as is necessary or appropriate to fulfill the purpose of the visitor's interaction with Internet Radio Radio. Internet Radio Radio does not disclose personally-identifying information other than as described below. And visitors can always refuse to supply personally-identifying information, with the caveat that it may prevent them from engaging in certain website-related activities.</p>
		<h2>Aggregated Statistics</h2>
			<p>Internet Radio Radio may collect statistics about the behavior of visitors to its websites. Internet Radio Radio may display this information publicly or provide it to others. However, Internet Radio Radio does not disclose personally-identifying information other than as described below.</p>
		<h2>Protection of Certain Personally-Identifying Information</h2>
			<p>Internet Radio Radio discloses potentially personally-identifying and personally-identifying information only to those of its employees, contractors and affiliated organizations that (i) need to know that information in order to process it on Internet Radio Radio behalf or to provide services available at Internet Radio Radio websites, and (ii) that have agreed not to disclose it to others. Some of those employees, contractors and affiliated organizations may be located outside of your home country; by using Internet Radio Radio websites, you consent to the transfer of such information to them. Internet Radio Radio will not rent or sell potentially personally-identifying and personally-identifying information to anyone. Other than to its employees, contractors and affiliated organizations, as described above, Internet Radio Radio discloses potentially personally-identifying and personally-identifying information only in response to a subpoena, court order or other governmental request, or when Internet Radio Radio believes in good faith that disclosure is reasonably necessary to protect the property or rights of Internet Radio Radio, third parties or the public at large. If you are a registered user of an Internet Radio Radio website and have supplied your email address, Internet Radio Radio may occasionally send you an email to tell you about new features, solicit your feedback, or just keep you up to date with what's going on with Internet Radio Radio and our products. If you send us a request (for example via email or via one of our feedback mechanisms), we reserve the right to publish it in order to help us clarify or respond to your request or to help us support other users. Internet Radio Radio takes all measures reasonably necessary to protect against the unauthorized access, use, alteration or destruction of potentially personally-identifying and personally-identifying information.</p>
		<h2>Cookies</h2>
			<p>A cookie is a string of information that a website stores on a visitor's computer, and that the visitor's browser provides to the website each time the visitor returns. Internet Radio Radio uses cookies to help Internet Radio Radio identify and track visitors, their usage of Internet Radio Radio website, and their website access preferences. Internet Radio Radio visitors who do not wish to have cookies placed on their computers should set their browsers to refuse cookies before using Internet Radio Radio websites, with the drawback that certain features of Internet Radio Radio websites may not function properly without the aid of cookies.</p>
		<h2>Business Transfers</h2>
			<p>If Internet Radio Radio, or substantially all of its assets, were acquired, or in the unlikely event that Internet Radio Radio goes out of business or enters bankruptcy, user information would be one of the assets that is transferred or acquired by a third party. You acknowledge that such transfers may occur, and that any acquirer of Internet Radio Radio may continue to use your personal information as set forth in this policy.</p>
		<h2>Ads</h2>
			<p>Ads appearing on any of our websites may be delivered to users by advertising partners, who may set cookies. These cookies allow the ad server to recognize your computer each time they send you an online advertisement to compile information about you or others who use your computer. This information allows ad networks to, among other things, deliver targeted advertisements that they believe will be of most interest to you. This Privacy Policy covers the use of cookies by Internet Radio Radio and does not cover the use of cookies by any advertisers.</p>
		<h2>Privacy Policy Changes</h2>
			<p>Although most changes are likely to be minor, Internet Radio Radio may change its Privacy Policy from time to time, and in Internet Radio Radio sole discretion. Internet Radio Radio encourages visitors to frequently check this page for any changes to its Privacy Policy. If you have a Internet Radio Radio account, you might also receive an alert informing you of these changes. Your continued use of this site after any change in this Privacy Policy will constitute your acceptance of such change.</p>
	</section>	
</main>



@endsection